/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppDiamondsRouteImport } from './routes/_app.diamonds'
import { Route as AppMetalPricesRouteImport } from './routes/_app.metal-prices'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppQuotationIdRouteImport } from './routes/_app.quotation.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppDiamondsRoute = AppDiamondsRouteImport.update({
  id: '/diamonds',
  path: '/diamonds',
  getParentRoute: () => AppRoute,
} as any)
const AppMetalPricesRoute = AppMetalPricesRouteImport.update({
  id: '/metal-prices',
  path: '/metal-prices',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationIdRoute = AppQuotationIdRouteImport.update({
  id: '/quotation/$id',
  path: '/quotation/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/diamonds': typeof AppDiamondsRoute
  '/metal-prices': typeof AppMetalPricesRoute
  '/search': typeof AppSearchRoute
  '/quotation/$id': typeof AppQuotationIdRoute
}
export interface FileRoutesByTo {
  '/diamonds': typeof AppDiamondsRoute
  '/metal-prices': typeof AppMetalPricesRoute
  '/search': typeof AppSearchRoute
  '/': typeof AppIndexRoute
  '/quotation/$id': typeof AppQuotationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/diamonds': typeof AppDiamondsRoute
  '/_app/metal-prices': typeof AppMetalPricesRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/': typeof AppIndexRoute
  '/_app/quotation/$id': typeof AppQuotationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/diamonds' | '/metal-prices' | '/search' | '/quotation/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/diamonds' | '/metal-prices' | '/search' | '/' | '/quotation/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_app/diamonds'
    | '/_app/metal-prices'
    | '/_app/search'
    | '/_app/'
    | '/_app/quotation/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diamonds': {
      id: '/_app/diamonds'
      path: '/diamonds'
      fullPath: '/diamonds'
      preLoaderRoute: typeof AppDiamondsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metal-prices': {
      id: '/_app/metal-prices'
      path: '/metal-prices'
      fullPath: '/metal-prices'
      preLoaderRoute: typeof AppMetalPricesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotation/$id': {
      id: '/_app/quotation/$id'
      path: '/quotation/$id'
      fullPath: '/quotation/$id'
      preLoaderRoute: typeof AppQuotationIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDiamondsRoute: typeof AppDiamondsRoute
  AppMetalPricesRoute: typeof AppMetalPricesRoute
  AppSearchRoute: typeof AppSearchRoute
  AppIndexRoute: typeof AppIndexRoute
  AppQuotationIdRoute: typeof AppQuotationIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDiamondsRoute: AppDiamondsRoute,
  AppMetalPricesRoute: AppMetalPricesRoute,
  AppSearchRoute: AppSearchRoute,
  AppIndexRoute: AppIndexRoute,
  AppQuotationIdRoute: AppQuotationIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
