CREATE TABLE public.diamonds (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shape TEXT NOT NULL,
  mm TEXT NOT NULL,
  price_ct NUMERIC NOT NULL DEFAULT 0,
  natural_price_ct NUMERIC NOT NULL DEFAULT 0,
  moiss_price_ct NUMERIC NOT NULL DEFAULT 0,
  mm_shape TEXT GENERATED ALWAYS AS (shape || '-' || mm || ' MM') STORED,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX diamonds_shape_idx ON public.diamonds (shape);
GRANT ALL ON public.diamonds TO service_role;
GRANT INSERT ON public.diamonds TO anon;
ALTER TABLE public.diamonds ENABLE ROW LEVEL SECURITY;
CREATE POLICY "temp_seed_insert" ON public.diamonds FOR INSERT TO anon WITH CHECK (true);

CREATE TABLE public.metal_prices (
  purity TEXT PRIMARY KEY,
  price NUMERIC NOT NULL DEFAULT 0,
  making_charge NUMERIC NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT ALL ON public.metal_prices TO service_role;
ALTER TABLE public.metal_prices ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.quotations (
  id TEXT PRIMARY KEY,
  id_sku TEXT NOT NULL,
  category TEXT,
  images JSONB NOT NULL DEFAULT '[]'::jsonb,
  metal_items JSONB NOT NULL DEFAULT '[]'::jsonb,
  diamond_items JSONB NOT NULL DEFAULT '[]'::jsonb,
  summary JSONB NOT NULL DEFAULT '{}'::jsonb,
  quotation_date TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX quotations_date_idx ON public.quotations (quotation_date DESC);
CREATE INDEX quotations_sku_idx ON public.quotations (id_sku);
CREATE INDEX quotations_category_idx ON public.quotations (category);
GRANT ALL ON public.quotations TO service_role;
ALTER TABLE public.quotations ENABLE ROW LEVEL SECURITY;

CREATE SEQUENCE public.quotation_seq START 1;
GRANT ALL ON SEQUENCE public.quotation_seq TO service_role;

CREATE TABLE public.app_config (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT ALL ON public.app_config TO service_role;
ALTER TABLE public.app_config ENABLE ROW LEVEL SECURITY;

INSERT INTO public.app_config (key, value) VALUES ('app_password', 'lepdo1234');

INSERT INTO public.metal_prices (purity, price, making_charge, sort_order) VALUES
('9KT', 3960, 800, 0),
('10KT', 4410, 800, 1),
('14KT', 6077, 800, 2),
('18KT', 7462, 800, 3),
('22KT', 9000, 800, 4),
('24KT', 9800, 800, 5),
('Silver', 100, 250, 6),
('Platinum', 3200, 1250, 7);